language: node_js
before_install:
  - "npm install npm -g"
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
node_js:
  - 5
  - 4
env:
  global:
   - secure: QvL5ON9lyZ8+BqnWHwYTQ35AWOhlxKFfmW1GbV+QA502M8P89DcjnjVasJkXQ5PSiHdlPyJD0HKxi9M7zjsP/9g6XP3CPLn/xCtMzMqv0Pzu7xilzOBAeQ2cuo6R3CK0sMxDATQ6hBQwtJEqrbaoaxjDfSvyHz9Thqvmzbsa2LgNzQtiSqdvfChMuQCsiCNPb44XEzUXCOusl28IVjVeH/MEDhFCUhM6vKCM/7NzEM7Lcu3uriXLnHjkKbJgVBFkeNyXLFJ99sn4JSNLt50Fjt3RaApOwVGsLBGaYhsRcuKBLBysn4DnnLBDUEwDvCCdWKyWthwzylS4SQBQv6m0yN79hCEgvFLzgRpSVxkEp2FSUcyV3xQy5hRtHrJgjpyimR+2YSo1N4BvsGdQAz9nhR3mgBm/+drFfgwMYgPqSOrQ+TPTFl9zhQ9xDozfodCkvbwDukr+z4Gqnxl12g7O65DhxP2wbzj5eRvNwf5Usmpk0jeoW3Kg5zTmW8fV5tjq5W4ZWFHf2+MDTmwqncw5y9HqNFPWQe0g7QxzaySkH4Z24/UKvgNckY2SCZ6V5EgJbm9fAt25jSC6UApZ2jZfd6KOtaL1qYDyyY2bAh9ge57xIMegfnapJE82CgdKgYuA5Ob/5CNbk1O0HsOaCwDfMbRNCSWCGPjyCUfpyEmvrv0=
  matrix:
   - TEST_SUITE=unit
   - TEST_SUITE=coveralls
script: "npm run-script $TEST_SUITE"
addons:
  coverity_scan:
    project:
      name: "davidszanto/coinkey"
    notification_email: cszoolee@gmail.com
    build_command_prepend: ""
    build_command:   ""
    branch_pattern: coverity_scan
